# Generated by Django 4.0.1 on 2022-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('Coach', 'Coach'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Student', 'Student'), ('Parent', 'Parent')], default='Undefined', max_length=20),
        ),
    ]
