# Generated by Django 4.0.1 on 2022-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_studentsgroup_alter_userprofile_group_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsgroup',
            name='group_name',
            field=models.CharField(default='NewGroup', max_length=100, unique=True),
        ),
    ]
