# Generated by Django 4.0.1 on 2022-02-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_studentsgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentsgroup'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, to='users.UserProfile'),
        ),
    ]
