# Generated by Django 4.0.1 on 2022-02-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_children_alter_userprofile_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='children',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='parents',
        ),
    ]
