# Generated by Django 4.0.1 on 2022-02-09 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_rename_userprofile_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='status',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('Coach', 'Coach'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist')], default='Undefined', max_length=20),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='YourPhone', max_length=12)),
                ('picture', models.ImageField(blank=True, default='default_user.jpg', upload_to='users/')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentsgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='YourPhone', max_length=12)),
                ('picture', models.ImageField(blank=True, default='default_user.jpg', upload_to='users/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
