# Generated by Django 4.0.1 on 2022-02-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
