# Generated by Django 4.0.1 on 2022-02-09 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coaches', '0005_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='YourPhone', max_length=12)),
                ('picture', models.ImageField(blank=True, default='default_user.jpg', upload_to='users/')),
                ('status', models.CharField(choices=[('Undefined', 'Undefined'), ('Coach', 'Coach'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist')], default='Undefined', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
